version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/app
    ports:
      - "8443:8443"
    depends_on:
      - redis
    command: /bin/bash /app/docker-entrypoint.sh
